[package]
name = "ownership"
version = "0.1.0"
authors = ["gusaroviv <gusaroviv@edu.mos.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
